# PRのラベルに応じてリリースノートのカテゴリを分ける
changelog:
  exclude:
    authors:
      - github-actions
  categories:
    - title: New Features
      labels:
        - "1.機能"
    - title: Bug Fixes
      labels:
        - "2.バグ"
    - title: UI/UX
      labels:
        - "3.UI/UX"
    - title: インフラ
      labels:
        - "4.インフラ"
    - title: リファクタリング
      labels:
        - "5.リファクタリング"
    - title: テスト
      labels:
        - "6.テスト"
    - title: Other Changes
      labels:
        - "*"