name: Create a pull request for release.

on:
  push:
    branches: [ staging1, develop ]

jobs:
  create-release-pr:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      # リリース用PRが既に存在するかどうかをチェック
      - name: Check if pr exists
        id: check_pr
        run: |
          pr_title=${{ (github.ref == 'refs/heads/staging1' && 'stg2main') || 'dev2stg' }}
          base_branch=${{ (github.ref == 'refs/heads/staging1' && 'main') || 'staging1' }}
          echo "count=$(gh pr list -S ${pr_title}' in:title' -B $base_branch | wc -l)" >> $GITHUB_ENV
          echo "pr_title=$pr_title" >> $GITHUB_ENV
          echo "base_branch=$base_branch" >> $GITHUB_ENV
      # リリース用PRを作成
      - name: Create release pr
        if: ${{ env.count == 0 }}
        run: |
          gh pr create -B ${{ env.base_branch }} -t ${{ env.pr_title }} -b ""
