name: Release Drafter

on:
  pull_request:
    types: [closed]
    branches:
      - main  # ここも同様に変更してください

jobs:
  update_release:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          publish: true


